[build]
builder = "nixpacks"
buildCommand = "bundle install && bundle exec rake assets:precompile"

[deploy]
startCommand = "bundle exec puma -C config/puma.rb"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
RAILS_ENV = "production"
RAILS_SERVE_STATIC_FILES = "true" 