{
  "$schema": "https://railway.com/railway.schema.json",
  "build": {
    "builder": "DOCKERFILE",
    "buildCommand": "chmod +x bin/rails && bundle install && bundle exec rake assets:precompile",
    "dockerfilePath": "Dockerfile"
  },
  "deploy": {
    "runtime": "V2",
    "numReplicas": 1,
    "startCommand": "bundle exec puma -C config/puma.rb",
    "healthcheckPath": "/",
    "sleepApplication": false,
    "multiRegionConfig": {
      "asia-southeast1-eqsg3a": {
        "numReplicas": 1
      }
    },
    "restartPolicyType": "ALWAYS",
    "healthcheckTimeout": 100
  }
}
